-- MySQL Script generated by MySQL Workbench
-- Wed Dec  9 20:20:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vk` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vk` ;

-- -----------------------------------------------------
-- Table `vk`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`users` (
  `idusers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(145) NOT NULL COMMENT 'Имя',
  `lastname` VARCHAR(245) NOT NULL COMMENT 'Фамилия',
  `email` VARCHAR(245) NOT NULL,
  `phone` BIGINT(12) NOT NULL,
  `password_hash` CHAR(65) NULL DEFAULT NULL,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`media_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`media_types` (
  `idmedia_types` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmedia_types`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`media` (
  `idmedia` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_idusers` INT UNSIGNED NOT NULL,
  `media_types_idmedia_types` INT UNSIGNED NOT NULL,
  `name` VARCHAR(145) NOT NULL,
  `url` VARCHAR(45) NULL DEFAULT NULL,
  `blob` BLOB NULL DEFAULT NULL,
  `size` BIGINT NOT NULL DEFAULT 0,
  `metadata` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`idmedia`),
  INDEX `fk_media_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_media_media_types1_idx` (`media_types_idmedia_types` ASC) VISIBLE,
  CONSTRAINT `fk_media_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_media_types1`
    FOREIGN KEY (`media_types_idmedia_types`)
    REFERENCES `vk`.`media_types` (`idmedia_types`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`profiles` (
  `users_idusers` INT UNSIGNED NOT NULL,
  `gender` ENUM('m', 'f', 'x') NOT NULL,
  `photo_idmedia` INT UNSIGNED NULL DEFAULT NULL,
  `birthday` DATE NOT NULL,
  `adress` VARCHAR(345) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  INDEX `fk_profiles_users_idx` (`users_idusers` ASC) VISIBLE,
  PRIMARY KEY (`users_idusers`),
  INDEX `fk_profiles_media1_idx` (`photo_idmedia` ASC) VISIBLE,
  CONSTRAINT `fk_profiles_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profiles_media1`
    FOREIGN KEY (`photo_idmedia`)
    REFERENCES `vk`.`media` (`idmedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`friend_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`friend_requests` (
  `from_users_idusers` INT UNSIGNED NOT NULL,
  `to_users_idusers` INT UNSIGNED NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '-1 denied, 0 request, 1 accepted',
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `updated_at` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_friend_requests_users1_idx` (`from_users_idusers` ASC) VISIBLE,
  INDEX `fk_friend_requests_users2_idx` (`to_users_idusers` ASC) VISIBLE,
  PRIMARY KEY (`from_users_idusers`, `to_users_idusers`),
  CONSTRAINT `fk_friend_requests_users1`
    FOREIGN KEY (`from_users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friend_requests_users2`
    FOREIGN KEY (`to_users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`messages` (
  `idmessages` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `from_users_idusers` INT UNSIGNED NOT NULL,
  `to_users_idusers` INT UNSIGNED NOT NULL,
  `text` VARCHAR(345) NULL DEFAULT NULL,
  `media_idmedia` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idmessages`),
  INDEX `from_users_idx` (`from_users_idusers` ASC) VISIBLE,
  INDEX `fk_messages_users1_idx` (`to_users_idusers` ASC) VISIBLE,
  INDEX `fk_messages_media1_idx` (`media_idmedia` ASC) VISIBLE,
  CONSTRAINT `fk_messages_users_from`
    FOREIGN KEY (`from_users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users_to`
    FOREIGN KEY (`to_users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_media1`
    FOREIGN KEY (`media_idmedia`)
    REFERENCES `vk`.`media` (`idmedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`communities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`communities` (
  `idcommunities` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(145) NOT NULL,
  `description` VARCHAR(245) NULL DEFAULT NULL,
  `admin_idusers` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcommunities`),
  INDEX `fk_communities_users1_idx` (`admin_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_communities_users1`
    FOREIGN KEY (`admin_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`users_communities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`users_communities` (
  `communities_idcommunities` INT UNSIGNED NOT NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  INDEX `fk_users_communities_communities1_idx` (`communities_idcommunities` ASC) VISIBLE,
  INDEX `fk_users_communities_users1_idx` (`users_idusers` ASC) VISIBLE,
  PRIMARY KEY (`communities_idcommunities`, `users_idusers`),
  CONSTRAINT `fk_users_communities_communities1`
    FOREIGN KEY (`communities_idcommunities`)
    REFERENCES `vk`.`communities` (`idcommunities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_communities_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`posts` (
  `idposts` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL DEFAULT NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  `communities_idcommunities` INT UNSIGNED NULL DEFAULT NULL,
  `media_idmedia` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idposts`),
  INDEX `fk_posts_users1_idx` (`users_idusers` ASC) VISIBLE,
  INDEX `fk_posts_communities1_idx` (`communities_idcommunities` ASC) VISIBLE,
  INDEX `fk_posts_media1_idx` (`media_idmedia` ASC) VISIBLE,
  CONSTRAINT `fk_posts_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_communities1`
    FOREIGN KEY (`communities_idcommunities`)
    REFERENCES `vk`.`communities` (`idcommunities`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_posts_media1`
    FOREIGN KEY (`media_idmedia`)
    REFERENCES `vk`.`media` (`idmedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`likes` (
  `from_users_idusers` INT UNSIGNED NOT NULL,
  `to_users_idusers1` INT UNSIGNED NOT NULL,
  `posts_idposts` INT UNSIGNED NOT NULL,
  `media_idmedia` INT UNSIGNED NOT NULL,
  INDEX `fk_likes_users1_idx` (`from_users_idusers` ASC) VISIBLE,
  INDEX `fk_likes_users2_idx` (`to_users_idusers1` ASC) VISIBLE,
  PRIMARY KEY (`from_users_idusers`, `to_users_idusers1`),
  INDEX `fk_likes_posts1_idx` (`posts_idposts` ASC) VISIBLE,
  INDEX `fk_likes_media1_idx` (`media_idmedia` ASC) VISIBLE,
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`from_users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_users2`
    FOREIGN KEY (`to_users_idusers1`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_posts1`
    FOREIGN KEY (`posts_idposts`)
    REFERENCES `vk`.`posts` (`idposts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_media1`
    FOREIGN KEY (`media_idmedia`)
    REFERENCES `vk`.`media` (`idmedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vk`.`mini-apps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vk`.`mini-apps` (
  `idmini-apps` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(145) NOT NULL,
  `media_idmedia` INT UNSIGNED NOT NULL,
  `users_idusers` INT UNSIGNED NOT NULL,
  `url` VARCHAR(245) NOT NULL COMMENT '/games-miniapps.com',
  PRIMARY KEY (`idmini-apps`),
  INDEX `fk_mini-apps_media1_idx` (`media_idmedia` ASC) VISIBLE,
  INDEX `fk_mini-apps_users1_idx` (`users_idusers` ASC) VISIBLE,
  CONSTRAINT `fk_mini-apps_media1`
    FOREIGN KEY (`media_idmedia`)
    REFERENCES `vk`.`media` (`idmedia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mini-apps_users1`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `vk`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
